spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AOUTH2_SAMPLEPROJECT_ID}
          kakao:
            client-id: ${KAKAO_AOUTH2_ID}


logging.level:
  org.hibernate.SQL: debug

#mail:
#  address:
#    admin: ${ADMIN_EMAIL}

#server:
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit
