spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AOUTH2_SAMPLEPROJECT_ID}
            scope:
              - email
              - profile


logging.level:
  org.hibernate.SQL: debug

#mail:
#  address:
#    admin: ${ADMIN_EMAIL}

#jwt:
#  key:
#    secret: ${JWT_SECRET_KEY}
#  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
#  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}
#server:
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit
